# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mai', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('span1', models.CharField(max_length=20)),
                ('span2', models.CharField(max_length=20)),
                ('goodsid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('passWordtext', models.CharField(max_length=256)),
            ],
        ),
    ]
