# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('bigImg', models.CharField(max_length=20)),
                ('alt', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('smallimg1', models.CharField(max_length=20)),
                ('smallimg2', models.CharField(max_length=20)),
                ('smallimg3', models.CharField(max_length=20)),
                ('producttitle', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=20)),
                ('currentprice', models.CharField(max_length=20)),
                ('originalprice', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('selectimg', models.CharField(max_length=20)),
                ('selectcolor', models.CharField(max_length=20)),
                ('choosesize1', models.CharField(max_length=20)),
                ('choosesize2', models.CharField(max_length=20)),
                ('choosesize3', models.CharField(max_length=20)),
                ('changtu', models.CharField(max_length=20)),
            ],
        ),
    ]
