# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_goodsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='alt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='bigImg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='changtu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='choosesize1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='choosesize2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='choosesize3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='currentprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='goodid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='originalprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='productname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='producttitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='selectcolor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='selectimg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='smallimg1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='smallimg2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='smallimg3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
