# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181101_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='product',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='productname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
